[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.build]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix frontend",
  "npm run build --prefix frontend"
]

[start]
cmd = "node backend/server.js"